---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liwenjie.
--- DateTime: 2019/4/28 9:32
---

-- Redis简单限流

local key = KEYS[1]
local threshold = tonumber(ARGV[1])
local ttl = ARGV[2]

-- 如果key存在，则val + 1
if redis.call('exists', key) == 1 then
    -- 如果expireTime时间内，val大于limit数，则启动限流，返回0
    if redis.call('incr', key) > threshold then
        return 0
    else
        return 1
    end
else
    -- 如果不存在key , 则初始化， val = 1
    redis.call('set', key, 1)
    redis.call('expire', key, ttl)
    return 1
end