---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liwenjie.
--- DateTime: 2019/4/26 16:16
---


-- 获得锁，如果成功，就给锁一个超时时间
if redis.call('setnx', KEYS[1], ARGV[1]) == 1 then
    redis.call('expire', KEYS[1], ARGV[2])
    return 1

else
    -- 如果没有获得锁，则返回失败
    return 0
end
